# Generated by Django 5.2.7 on 2025-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LGDInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.IntegerField(verbose_name='LGD District Code')),
                ('district_name', models.CharField(max_length=100, verbose_name='District Name')),
                ('sub_district', models.IntegerField(verbose_name='LGD Sub-District Code')),
                ('sub_district_name', models.CharField(max_length=100, verbose_name='Sub-District Name')),
                ('village', models.IntegerField(verbose_name='LGD Village Code')),
                ('village_name', models.CharField(max_length=100, verbose_name='Village Name')),
            ],
            options={
                'verbose_name': 'LGD Information',
                'verbose_name_plural': 'LGD Information',
                'indexes': [models.Index(fields=['district', 'sub_district', 'village'], name='lgd_lgdinfo_distric_59e2fe_idx'), models.Index(fields=['district_name'], name='lgd_lgdinfo_distric_6665f2_idx'), models.Index(fields=['village_name'], name='lgd_lgdinfo_village_e2f77a_idx')],
            },
        ),
    ]
