# Generated by Django 5.2.7 on 2025-11-21 18:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Product category name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Category description')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=50, unique=True, verbose_name='Unit name (e.g., kg, pcs)')),
                ('description', models.CharField(blank=True, max_length=100, null=True, verbose_name='Description of the unit')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_code', models.CharField(max_length=50, unique=True, verbose_name='Product code / SKU')),
                ('name', models.CharField(max_length=200, verbose_name='Variant name')),
                ('size', models.DecimalField(decimal_places=2, help_text='The numeric size, like 14.2 or 19.0', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Size must be greater than zero')], verbose_name='Size (e.g., weight or volume)')),
                ('variant_type', models.CharField(choices=[('DOMESTIC', 'Domestic'), ('COMMERCIAL', 'Commercial'), ('INDUSTRIAL', 'Industrial'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, help_text='Current price for this variant', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='Price must be greater than zero')], verbose_name='Current selling price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='variants', to='products.product', verbose_name='Parent product category')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.unit', verbose_name='Unit of measurement')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Variants',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price before the change', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Previous price')),
                ('new_price', models.DecimalField(decimal_places=2, help_text='Price after the change', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'), message='New price must be greater than zero')], verbose_name='New price')),
                ('price_change', models.DecimalField(decimal_places=2, help_text='Difference (new - old)', max_digits=10, verbose_name='Price change amount')),
                ('price_change_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage change', max_digits=6, null=True, verbose_name='Price change %')),
                ('effective_date', models.DateTimeField(auto_now_add=True, help_text='When this price became effective', verbose_name='Effective date')),
                ('reason', models.CharField(blank=True, help_text='Optional reason for price change', max_length=200, verbose_name='Reason for change')),
                ('notes', models.TextField(blank=True, help_text='Any additional information', verbose_name='Additional notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_changes', to=settings.AUTH_USER_MODEL, verbose_name='Changed by')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.productvariant', verbose_name='Product variant')),
            ],
            options={
                'verbose_name': 'Product Variant Price History',
                'verbose_name_plural': 'Product Variant Price History',
                'ordering': ['-effective_date'],
                'indexes': [models.Index(fields=['-effective_date'], name='products_pr_effecti_7b2754_idx'), models.Index(fields=['variant', '-effective_date'], name='products_pr_variant_1ede9e_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['product', 'variant_type'], name='products_pr_product_4952c7_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['variant_type'], name='products_pr_variant_ef6d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='productvariant',
            index=models.Index(fields=['price'], name='products_pr_price_a59bc5_idx'),
        ),
    ]
