# Generated by Django 5.2.7 on 2025-11-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='House number')),
                ('house_name_flat_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Flat or building name')),
                ('housing_complex_building', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complex name')),
                ('street_road_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Street name')),
                ('land_mark', models.CharField(blank=True, max_length=150, null=True, verbose_name='Nearby landmark')),
                ('city_town_village', models.CharField(blank=True, max_length=100, null=True, verbose_name='City or village')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='District name')),
                ('pin_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Postal code')),
                ('address_text', models.TextField(blank=True, null=True, verbose_name='Full Address Text')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Addresses',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='address_add_content_c8c3a6_idx'), models.Index(fields=['pin_code'], name='address_add_pin_cod_0aff1d_idx'), models.Index(fields=['city_town_village'], name='address_add_city_to_e59f2d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='Email ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Landline number')),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='Mobile number')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='address_con_content_4df061_idx'), models.Index(fields=['mobile_number'], name='address_con_mobile__c85ce5_idx'), models.Index(fields=['email'], name='address_con_email_d2f0e2_idx')],
            },
        ),
    ]
