# Generated by Django 5.2.7 on 2025-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('referer', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.IntegerField(default=500)),
                ('error_type', models.CharField(max_length=100)),
                ('error_message', models.TextField()),
                ('traceback', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(max_length=10)),
                ('path', models.CharField(max_length=255)),
                ('referer', models.CharField(blank=True, max_length=255, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
