# Generated by Django 5.2.7 on 2025-10-26 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
        ('routes', '0001_initial'),
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(max_length=50, unique=True)),
                ('consumer_name', models.CharField(max_length=200)),
                ('father_name', models.CharField(blank=True, max_length=200, null=True)),
                ('mother_name', models.CharField(blank=True, max_length=200, null=True)),
                ('spouse_name', models.CharField(blank=True, max_length=200, null=True)),
                ('ration_card_num', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ration Card Number')),
                ('blue_book', models.PositiveIntegerField(blank=True, null=True, verbose_name='Blue Book Number')),
                ('lpg_id', models.PositiveBigIntegerField(blank=True, null=True, unique=True, verbose_name='LPG ID')),
                ('is_kyc_done', models.BooleanField(default=False, verbose_name='KYC Status')),
                ('opting_status', models.CharField(choices=[('OPT_IN', 'Opt In'), ('OPT_OUT', 'Opt Out'), ('PENDING', 'Pending')], default='PENDING', max_length=20)),
                ('bpl_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lookups.bpltype')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookups.consumercategory')),
                ('consumer_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookups.consumertype')),
                ('dct_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='lookups.dcttype', verbose_name='DCT Type')),
                ('scheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schemes.scheme')),
            ],
        ),
        migrations.CreateModel(
            name='ConsumerRouteAssignmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(blank=True, max_length=50)),
                ('consumer_name', models.CharField(blank=True, max_length=200)),
                ('route_code', models.CharField(blank=True, max_length=50)),
                ('route_description', models.CharField(blank=True, max_length=150)),
                ('action_type', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('DELETED', 'Deleted')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('consumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='consumers.consumer')),
                ('route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='routes.route')),
            ],
            options={
                'verbose_name': 'Consumer Route Assignment History',
                'verbose_name_plural': 'Consumer Route Assignment History',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ConsumerRouteAssignment',
            fields=[
                ('consumer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='route_assignment', serialize=False, to='consumers.consumer')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumer_assignments', to='routes.route')),
            ],
            options={
                'verbose_name': 'Consumer Route Assignment',
                'verbose_name_plural': 'Consumer Route Assignments',
            },
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['consumer_name'], name='consumers_c_consume_a9103d_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['opting_status'], name='consumers_c_opting__9c0e0a_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['is_kyc_done'], name='consumers_c_is_kyc__06ac37_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['category', 'consumer_type'], name='consumers_c_categor_86f3df_idx'),
        ),
        migrations.AddIndex(
            model_name='consumer',
            index=models.Index(fields=['scheme'], name='consumers_c_scheme__ae5229_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignmenthistory',
            index=models.Index(fields=['-timestamp'], name='consumers_c_timesta_bee9e7_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignmenthistory',
            index=models.Index(fields=['consumer', 'timestamp'], name='consumers_c_consume_4d334b_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignmenthistory',
            index=models.Index(fields=['route', 'timestamp'], name='consumers_c_route_i_65acf7_idx'),
        ),
        migrations.AddIndex(
            model_name='consumerrouteassignment',
            index=models.Index(fields=['route'], name='consumers_c_route_i_36eb32_idx'),
        ),
    ]
