# Generated by Django 5.2.7 on 2025-11-21 18:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubsidyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2026)], verbose_name='Applicable subsidy year')),
                ('quota', models.PositiveIntegerField(verbose_name='Total quota allotted')),
                ('delivered', models.PositiveIntegerField(default=0, verbose_name='Quota delivered so far')),
            ],
            options={
                'verbose_name_plural': 'Subsidy Details',
            },
        ),
    ]
