# Generated by Django 5.2.7 on 2025-11-21 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumers', '0001_initial'),
        ('lookups', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConnectionDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sv_number', models.CharField(max_length=50, unique=True, verbose_name='Service number')),
                ('sv_date', models.DateField(verbose_name='Service initiation date')),
                ('hist_code_description', models.CharField(blank=True, max_length=150, null=True, verbose_name='History/category description')),
                ('num_of_regulators', models.PositiveIntegerField(default=1, verbose_name='Number of Regulators')),
                ('connection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lookups.connectiontype', verbose_name='Connection Type')),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='consumers.consumer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.productvariant', verbose_name='Product')),
            ],
            options={
                'verbose_name': 'Connection Details',
                'verbose_name_plural': 'Connection Details',
                'indexes': [models.Index(fields=['consumer', 'connection_type'], name='connections_consume_ebbe94_idx'), models.Index(fields=['sv_date'], name='connections_sv_date_ae9746_idx'), models.Index(fields=['product'], name='connections_product_a74db2_idx')],
            },
        ),
    ]
