# Generated by Django 5.2.7 on 2025-11-21 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consumers', '0001_initial'),
        ('delivery', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Flag',
                'verbose_name_plural': 'Delivery Flags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Payment Option',
                'verbose_name_plural': 'Payment Options',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RefillType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Refill Type',
                'verbose_name_plural': 'Refill Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_type', models.CharField(choices=[('PENDING', 'Pending Orders'), ('DELIVERY', 'Delivery Marking')], help_text='Type of upload this configuration applies to', max_length=20)),
                ('field_name', models.CharField(help_text="OrderBook model field name (e.g., 'consumer', 'order_no')", max_length=100)),
                ('is_included', models.BooleanField(default=True, help_text='Include this field in column mapping for this upload type')),
                ('is_required', models.BooleanField(default=False, help_text='Override: Is this field required for this upload type?')),
                ('display_order', models.IntegerField(default=0, help_text='Order in which field appears in mapping dialog')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Field Configuration',
                'verbose_name_plural': 'Field Configurations',
                'ordering': ['upload_type', 'display_order', 'field_name'],
                'indexes': [models.Index(fields=['upload_type'], name='order_book__upload__ccf044_idx'), models.Index(fields=['upload_type', 'is_included'], name='order_book__upload__a0ae66_idx')],
                'unique_together': {('upload_type', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='OrderBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=30)),
                ('book_date', models.DateField()),
                ('product', models.CharField(blank=True, default='', help_text='Product name', max_length=100)),
                ('delivery_date', models.DateField(blank=True, help_text='Actual delivery date', null=True)),
                ('last_delivery_date', models.DateTimeField(blank=True, help_text='Last delivery date from CSV bulk upload', null=True)),
                ('source_file', models.CharField(blank=True, help_text='Source file name for bulk uploads', max_length=255)),
                ('updated_type', models.CharField(choices=[('BULK', 'Bulk Upload'), ('MANUAL', 'Manual Update')], default='MANUAL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders', to='consumers.consumer')),
                ('delivery_flag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order_book.deliveryflag')),
                ('delivery_person', models.ForeignKey(blank=True, help_text='Delivery person who delivered this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_orders', to='delivery.deliveryperson')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_updates', to=settings.AUTH_USER_MODEL)),
                ('refill_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='order_book.refilltype')),
            ],
            options={
                'ordering': ['book_date', 'order_no'],
            },
        ),
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_memo_no', models.CharField(blank=True, help_text='Cash memo number from delivery', max_length=50)),
                ('payment_date', models.DateField(blank=True, help_text='Date of payment', null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Payment amount', max_digits=10, null=True)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('transaction_id', models.CharField(blank=True, default=None, help_text='Transaction ID for online payments', max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(help_text='Related order', on_delete=django.db.models.deletion.CASCADE, related_name='payment_info', to='order_book.orderbook')),
                ('payment_option', models.ForeignKey(blank=True, help_text='Payment method (Cash, Online, etc.)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='order_book.paymentoption')),
            ],
            options={
                'verbose_name': 'Payment Info',
                'verbose_name_plural': 'Payment Info',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BulkUploadHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Name of uploaded file', max_length=255)),
                ('file_type', models.CharField(help_text='File type: CSV or XLSX', max_length=10)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('upload_type', models.CharField(choices=[('PENDING', 'Pending Orders'), ('DELIVERY', 'Delivery Marking')], help_text='Type of upload: PENDING or DELIVERY', max_length=20)),
                ('row_count', models.IntegerField(help_text='Number of data rows (excluding header)')),
                ('success_count', models.IntegerField(default=0, help_text='Number of successfully processed rows')),
                ('error_count', models.IntegerField(default=0, help_text='Number of rows with errors')),
                ('skipped_count', models.IntegerField(blank=True, default=0, help_text='Number of skipped rows', null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('PARTIAL', 'Partial Success'), ('FAILED', 'Failed')], help_text='Overall upload status', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('error_summary', models.TextField(blank=True, help_text='Summary of errors (max 5000 chars)', null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bulk Upload History',
                'verbose_name_plural': 'Bulk Upload Histories',
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['upload_type'], name='order_book__upload__999c2f_idx'), models.Index(fields=['status'], name='order_book__status_cc5930_idx'), models.Index(fields=['-uploaded_at'], name='order_book__uploade_d1f489_idx')],
            },
        ),
        migrations.CreateModel(
            name='ColumnMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Mapping configuration name', max_length=100)),
                ('upload_type', models.CharField(blank=True, choices=[('PENDING', 'Pending Orders'), ('DELIVERY', 'Delivery Marking')], default='', help_text='Type of upload this mapping is for (PENDING or DELIVERY)', max_length=20)),
                ('file_format', models.CharField(choices=[('CSV', 'CSV File'), ('EXCEL', 'Excel File')], default='CSV', help_text='File format this mapping is for (CSV or EXCEL)', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('mappings', models.JSONField(help_text='Column mapping dictionary')),
                ('is_active', models.BooleanField(default=True, help_text='Is this mapping active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='column_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Column Mapping',
                'verbose_name_plural': 'Column Mappings',
                'ordering': ['upload_type', 'file_format'],
                'unique_together': {('upload_type', 'file_format')},
            },
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['consumer'], name='order_book__consume_7cb9c2_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['order_no', 'book_date'], name='order_book__order_n_b1da63_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['-book_date'], name='order_book__book_da_5566cf_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['delivery_flag'], name='order_book__deliver_519ff8_idx'),
        ),
        migrations.AddIndex(
            model_name='orderbook',
            index=models.Index(fields=['delivery_person'], name='order_book__deliver_865bc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='orderbook',
            unique_together={('consumer', 'order_no', 'book_date')},
        ),
    ]
